//Get Commant
export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAIL    = 'COMMENT_FAIL'

// Create Comment
export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAIL    = 'POST_COMMENT_FAIL'

//Edit Comment
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAIL    = 'EDIT_COMMENT_FAIL'

// Delete Comment
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL    = 'DELETE_COMMENT_FAIL'
// DELETE_COMMENT_REQUEST,DELETE_COMMENT_SUCCESS,DELETE_COMMENT_FAIL