export const CHAT_ID_REQUEST = 'CHAT_ID_REQUEST'
export const CHAT_ID_SUCCESS = 'CHAT_ID_SUCCESS'
export const CHAT_ID_FAIL    = 'CHAT_ID_FAIL'

// Chat message
export const  CHAT_REQUEST = 'CHAT_REQUEST'
export const  CHAT_SUCCESS = 'CHAT_SUCCESS'
export const  CHAT_FAIL    = 'CHAT_FAIL'

// Mark_read
export const MARK_READ_REQUEST = 'MARK_READ_REQUEST'
export const MARK_READ_SUCCESS = 'MARK_READ_SUCCESS'
export const MARK_READ_FAIL    = 'MARK_READ_FAIL'

export const CLEAR_UNREAD_COUNT = 'CLEAR_UNREAD_COUNT'
export const UPDATE_MESSAGE_COUNT = "UPDATE_MESSAGE_COUNT"

// online-status
export const USER_ONLINE_STATUS_REQUEST = 'USER_ONLINE_STATUS_REQUEST'
export const USER_ONLINE_STATUS_SUCCESS = 'USER_ONLINE_STATUS_SUCCESS'
export const USER_ONLINE_STATUS_FAIL    = 'USER_ONLINE_STATUS_FAIL'

// Unread message
export const UNREAD_MESSAGE_COUNT_REQUEST = 'UNREAD_MESSAGE_COUNT_REQUEST'
export const UNREAD_MESSAGE_COUNT_SUCCESS = 'UNREAD_MESSAGE_COUNT_SUCCESS'
export const UNREAD_MESSAGE_COUNT_FAIL    = 'UNREAD_MESSAGE_COUNT_FAIL'

// Last message
export const LAST_MESSAGE_REQUEST = 'LAST_MESSAGE_REQUEST'
export const LAST_MESSAGE_SUCCESS = 'LAST_MESSAGE_SUCCESS'
export const LAST_MESSAGE_FAIL    = 'LAST_MESSAGE_FAIL'
export const LAST_MESSAGE_UPDATE  = 'LAST_MESSAGE_UPDATE'