export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_FAIL    = 'NOTIFICATION_FAIL'


export const NOTIFICATION_DELETE_REQUEST ='NOTIFICATION_DELETE_REQUEST'
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const NOTIFICATION_DELETE_FAIL    = 'NOTIFICATION_DELETE_FAIL'


export const UNREAD_REQUEST = 'UNREAD_REQUEST'
export const UNREAD_SUCCESS = 'UNREAD_SUCCESS'
export const UNREAD_FAIL    = 'UNREAD_FAIL'

export const UPDATE_NOTIFICATION_COUNT = 'UPDATE_NOTIFICATION_COUNT'


export const MARK_READ_REQUEST = 'MARK_READ_REQUEST'
export const MARK_READ_SUCCESS = 'MARK_READ_SUCCESS'
export const MARK_READ_FAIL    = 'MARK_READ_FAIL'