// Post reaction
export const REACTION_REQUEST = 'REACTION_REQUEST'
export const REACTION_SUCCESS = 'REACTION_SUCCESS'
export const REACTION_FAIL    = 'REACTION_FAIL'


// Comment reaction
export const COMMENT_REACTION_REQUEST = 'COMMENT_REACTION_REQUEST'
export const COMMENT_REACTION_SUCCESS = 'COMMENT_REACTION_SUCCESS'
export const COMMENT_REACTION_FAIL    = 'COMMENT_REACTION_FAIL'
