export const  PROFILE_INFO_REQUEST = 'PROFILE_INFO_REQUEST'
export const  PROFILE_INFO_SUCCESS = 'PROFILE_INFO_SUCCESS'
export const PROFILE_INFO_FAIL = 'PROFILE_INFO_FAIL'

// edit profile
export const  PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST'
export const  PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS'
export const  PROFILE_EDIT_FAIL    = 'PROFILE_EDIT_FAIL'
export const  PROFILE_EDIT_RESET    = 'PROFILE_EDIT_RESET'